
#The general configuration for this mod
[general]
	#If set to true Shields added by other mods block 100% of the incomming damage, if set to false the will block the amount set in defaultDamageReduction.
	#Default: true
	customShieldMaxReduction = true
	#The portion of the incomming damage Vanilla Shields block in percent.
	#Default: 75
	defaultDamageReduction = 75
	#The portion of the incomming damage Iron Shields block in percent.
	#Default: 90
	ironDamageReduction = 90
	#The portion of the incomming damage Gold Shields block in percent.
	#Default: 85
	goldDamageReduction = 85
	#The portion of the incomming damage Diamond Shields block in percent.
	#Default: 98
	diamondDamageReduction = 98
	#The portion of the incomming damage Netherite Shields block in percent.
	#Default: 100
	netheriteDamageReduction = 100
	#The durability of the Iron Shield.
	#Default: 920
	ironDurability = 504
	#The durability of the Gold Shield.
	#Default: 130
	goldDurability = 420
	#The durability of the Diamond Shield.
	#Default: 4600
	diamondDurability = 2016
	#The durability of the Netherite Shield.
	#Default: 6300
	netheriteDurability = 2520
	#Allows the Thorns enchantment to by applied to Shields
	#Default: true
	thornsOnShields = true
	#Enables modified damage reduction values for shields.
	#Default: true
	enableDamageReduction = false

