
[General]
	#The message players will receive when they join a world for the first time.
	firstJoinMessage = "You feel that a book appears in your hands and is emitting an ancient energy."
	#The colour of the message. The possible values are; 0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white.
	#Range: 0 ~ 15
	firstJoinMessageTextFormattingColourIndex = 5

